# profile관리
spring:
  application:
    name: pettopia

#    active: prod

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: build/resources/main/static/ocr

logging:
  level:
    root: info
    com.sh: debug



  # 공통 jpa 설정
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
#          auto: none
          auto: update # update, create, create-drp, validate 중 선택

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  # NCP 클라우드 설정
cloud:
  aws:
    credentials:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}


application:
  bucket:
    name: pettopia-bucket
  #  user-id: ssgback3-3
file:
  upload-dir: /path/to/upload/directory

my:
  admin: 16091a7548fa162364eaec609653de3e

  # OCR 관련 설정
naver:
  clova-ocr:
    document:
      url: https://ajyqmi57wp.apigw.ntruss.com/custom/v1/33275/1211f29f3558eeccd1846ebd1e703c05e37a8295a4fcbca282d3bf85a4c43902/document/receipt
      secretKey: bmdZYXFQaXp1YnJQTk1FV0hNdXlRaHh3RFZ2alp5ZE8=